"""add job_id

Revision ID: 347aa640800b
Revises: 7cb59117b34a
Create Date: 2026-09-07 23:16:50.223690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '347aa640800b'
down_revision: Union[str, Sequence[str], None] = '7cb59117b34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'processing_jobs', ['job_id'], ['id'])
    op.add_column('review_actions', sa.Column('original_prediction_id', sa.UUID(), nullable=True))
    op.add_column('review_actions', sa.Column('corrected_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('review_actions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_actions', 'created_at')
    op.drop_column('review_actions', 'corrected_entities')
    op.drop_column('review_actions', 'original_prediction_id')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'job_id')
    # ### end Alembic commands ###
