"""Normalize schema

Revision ID: 7cb59117b34a
Revises: f0db6eaa6b69
Create Date: 2026-09-07 20:46:46.209794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cb59117b34a'
down_revision: Union[str, Sequence[str], None] = 'f0db6eaa6b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('life_saving_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_saving_rules_rule_code'), 'life_saving_rules', ['rule_code'], unique=True)
    op.create_table('lsr_rules_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('positive_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('danger_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('negative_contexts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lsr_rules_versions_rule_code'), 'lsr_rules_versions', ['rule_code'], unique=False)
    op.create_index(op.f('ix_lsr_rules_versions_version'), 'lsr_rules_versions', ['version'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('activity', sa.String(length=255), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('hazard', sa.String(length=255), nullable=True),
    sa.Column('failed_barrier', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('density', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('trend', sa.String(length=64), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['life_saving_rules.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patterns_rule_period', 'patterns', ['rule_id', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_patterns_site_period', 'patterns', ['site_id', 'period_start', 'period_end'], unique=False)
    op.create_table('barriers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('barrier_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_barriers_name_status', 'barriers', ['barrier_name', 'status'], unique=False)
    op.create_index('ix_barriers_report_status', 'barriers', ['report_id', 'status'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('normalized_value', sa.String(length=255), nullable=True),
    sa.Column('source_start', sa.Integer(), nullable=True),
    sa.Column('source_end', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_report_type', 'entities', ['report_id', 'entity_type'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_items_report', 'evidence_items', ['report_id'], unique=False)
    op.create_table('lsr_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('matched_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['life_saving_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lsr_predictions_report_current', 'lsr_predictions', ['report_id', 'is_current'], unique=False)
    op.create_index('ix_lsr_predictions_rule_current', 'lsr_predictions', ['rule_id', 'is_current'], unique=False)
    op.create_table('report_normalizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('normalization_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_normalizations_report_id'), 'report_normalizations', ['report_id'], unique=False)
    op.create_table('review_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('corrected_lsr_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sif_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('sif_potential', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_band', sa.String(length=32), nullable=False),
    sa.Column('engine_name', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('evidence_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sif_predictions_potential_created', 'sif_predictions', ['sif_potential', 'is_current'], unique=False)
    op.create_index('ix_sif_predictions_report_current', 'sif_predictions', ['report_id', 'is_current'], unique=False)
    op.create_index('ix_reports_site_reported', 'reports', ['site_id', 'reported_at'], unique=False)
    op.drop_column('reports', 'life_saving_rules')
    op.drop_column('reports', 'precursors')
    op.drop_column('reports', 'severity_score')
    op.drop_column('reports', 'extracted_hazards')
    op.drop_column('reports', 'root_causes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('root_causes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('extracted_hazards', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('severity_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('precursors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('life_saving_rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_reports_site_reported', table_name='reports')
    op.drop_index('ix_sif_predictions_report_current', table_name='sif_predictions')
    op.drop_index('ix_sif_predictions_potential_created', table_name='sif_predictions')
    op.drop_table('sif_predictions')
    op.drop_table('review_actions')
    op.drop_index(op.f('ix_report_normalizations_report_id'), table_name='report_normalizations')
    op.drop_table('report_normalizations')
    op.drop_index('ix_lsr_predictions_rule_current', table_name='lsr_predictions')
    op.drop_index('ix_lsr_predictions_report_current', table_name='lsr_predictions')
    op.drop_table('lsr_predictions')
    op.drop_index('ix_evidence_items_report', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index('ix_entities_report_type', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_barriers_report_status', table_name='barriers')
    op.drop_index('ix_barriers_name_status', table_name='barriers')
    op.drop_table('barriers')
    op.drop_index('ix_patterns_site_period', table_name='patterns')
    op.drop_index('ix_patterns_rule_period', table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_lsr_rules_versions_version'), table_name='lsr_rules_versions')
    op.drop_index(op.f('ix_lsr_rules_versions_rule_code'), table_name='lsr_rules_versions')
    op.drop_table('lsr_rules_versions')
    op.drop_index(op.f('ix_life_saving_rules_rule_code'), table_name='life_saving_rules')
    op.drop_table('life_saving_rules')
    # ### end Alembic commands ###
