"""Add vector and jsonb columns

Revision ID: a08133c97191
Revises: e0402b51fcf4
Create Date: 2026-09-06 21:15:09.178779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a08133c97191'
down_revision: Union[str, Sequence[str], None] = 'e0402b51fcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('extracted_hazards', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('root_causes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('severity_score', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('vector_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'vector_embedding')
    op.drop_column('reports', 'severity_score')
    op.drop_column('reports', 'root_causes')
    op.drop_column('reports', 'extracted_hazards')
    # ### end Alembic commands ###
