"""phase 1 fixes

Revision ID: e642610a5739
Revises: 347aa640800b
Create Date: 2026-09-08 11:17:38.156880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e642610a5739'
down_revision: Union[str, Sequence[str], None] = '347aa640800b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lsr_predictions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE lsr_predictions SET created_at = NOW()")
    op.alter_column('lsr_predictions', 'created_at', nullable=False)
    op.alter_column('processing_attempts', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('report_normalizations', sa.Column('uncertain_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('report_normalizations', sa.Column('preserved_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('report_normalizations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE report_normalizations SET created_at = NOW()")
    op.alter_column('report_normalizations', 'created_at', nullable=False)
    op.alter_column('reports', 'language_confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=True)
    op.alter_column('reports', 'sif_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=True)
    op.add_column('sif_predictions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE sif_predictions SET created_at = NOW()")
    op.alter_column('sif_predictions', 'created_at', nullable=False)
    op.alter_column('sif_predictions', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('sif_predictions', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sif_predictions', 'confidence',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sif_predictions', 'score',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.drop_column('sif_predictions', 'created_at')
    op.alter_column('reports', 'sif_score',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('reports', 'language_confidence',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.drop_column('report_normalizations', 'created_at')
    op.drop_column('report_normalizations', 'preserved_terms')
    op.drop_column('report_normalizations', 'uncertain_terms')
    op.alter_column('processing_attempts', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('lsr_predictions', 'created_at')
    # ### end Alembic commands ###
