"""Add Phase 6 to 9 columns

Revision ID: f0db6eaa6b69
Revises: a08133c97191
Create Date: 2026-09-06 22:29:27.455177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0db6eaa6b69'
down_revision: Union[str, Sequence[str], None] = 'a08133c97191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('sif_potential', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('sif_score', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('reports', sa.Column('risk_band', sa.String(length=32), nullable=True))
    op.add_column('reports', sa.Column('life_saving_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('precursors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'precursors')
    op.drop_column('reports', 'life_saving_rules')
    op.drop_column('reports', 'risk_band')
    op.drop_column('reports', 'sif_score')
    op.drop_column('reports', 'sif_potential')
    # ### end Alembic commands ###
